from os.path import splitext
from MediaName import MediaName
from MediaDate import MediaDate

class DefaultFilenameParser:
    """Parse a filename generated by the Media Organiser application: yyyy-mm-dd_hh.mm.ss_nnnnnn.ext"""

    @staticmethod
    def parse(filename):
        """This parser assumes that all fields are mandatory. If there is any field missing, it will fail."""
        name = DefaultFilenameParser.__removeFileExtension(filename)
        dateFromName = DefaultFilenameParser.__removeCounter(name)
        standardMetadataDateFormat = DefaultFilenameParser.__convertToMetadataFormat(dateFromName)
        print standardMetadataDateFormat
        return MediaName(MediaDate(standardMetadataDateFormat))

    @staticmethod
    def __removeFileExtension(filename):
        return splitext(filename)[0]

    @staticmethod
    def __removeCounter(name):
        parts = name.split('_')
        return '_'.join(parts[:2])

    @staticmethod
    def __convertToMetadataFormat(dateFromName):
        if len(dateFromName) < 10 or len(dateFromName) > 18:
            raise ValueError('File name ' + dateFromName + ' cannot be parsed.')
        return dateFromName.replace('-', ':').replace('.', ':').replace('_', ' ')
