from os.path import splitext
from MediaName import MediaName
from MediaDate import MediaDate

class MotorolaFilenameParser:
    """Parse a filename generated by a Motorola application: IMG_yyyymmdd_nnnnnnn.jpg"""

    @staticmethod
    def parse(filename):
        """This parser assumes that all fields are mandatory. If there is any field missing, it will fail."""
        dateFromFilename = MotorolaFilenameParser.__extractDate(filename)
        standardMetadataDateFormat = MotorolaFilenameParser.__convertToMetadataFormat(dateFromFilename)
        return MediaName(MediaDate(standardMetadataDateFormat, "Filename"))

    @staticmethod
    def __extractDate(name):
        date = name.replace('-', '_').split('_')[1]
        if len(date) != 8:
            raise ValueError('File name ' + date + ' cannot be parsed.')
        return date

    @staticmethod
    def __convertToMetadataFormat(dateFromName):
        return dateFromName[0:4] + ':' + dateFromName[4:6] + ':' + dateFromName[6:8]
